### ISSUE TITLE
SkyToastModule is missing BrowserAnimationsModule dependency

### ISSUE THREAD

**Issue by Blackbaud-ScottFreeman** [blackbaud/skyux-toast#13]
### Expected behavior
When creating a small spa with few dependencies listed in the skyuxModules property in skyuxconfig.json, listing the SkyToastModule should import everything required to use the toast feature.

### Actual behavior
SkyToastModule does not import BrowserAnimationsModule which is required for the feature to work.  This results in a runtime error when trying to show a toast.

### Steps to reproduce
1. Create a new spa using SkyUx CLI
2. Update skyuxconfig.json to include a skyuxModules property with only SkyToastModule.
3. Trim out everything so you only have the home component with a button to display a toast.
4. When pressing the button, you will receive a runtime error about the missing animations module.

### Severity
Low, easy workaround is to import the missing module yourself.

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.0.1`
