### ISSUE TITLE
Toasts should be viewable across SPAs

### ISSUE THREAD

**Issue by Blackbaud-ToddRoberts** [blackbaud/skyux-toast#15]
### Expected behavior
Toasts can be shown across SPAs (i.e. an action in one SPA can trigger a toast that shows up to the user regardless of which SPA they are currently viewing), and don't disappear when the user switches SPAs

### Actual behavior
Currently toasts can't be shown across SPAs and will disappear if the user switches SPAs even within the same Omnibar nav.

**Comment by Blackbaud-ToddRoberts** [comment]
RE NXT needs this for batch receipting, where the process can take a long time so users will want to go do other work while it processes, and then be notified where they are currently at in the system when it completes.

**Comment by Blackbaud-VinLanzolla** [comment]
FE needs this feature for long-running processes, e.g. computing actuals, generating large reports. Users will kick off the process and work in other SPAs/modules and rely on the toast to tell them their other process has completed.

**Comment by Blackbaud-MichaelCollier** [comment]
This issue will not be resolved as part of our open-source library.
