### ISSUE TITLE
Error when closing all toasts if no toasts are shown

### ISSUE THREAD

**Issue by Blackbaud-ChristiSchneider** [blackbaud/skyux-toast#19]
### Expected behavior
Calling `SkyToastService.closeAll()` will have no effect when no toasts have been shown

### Actual behavior
Console error is shown:
```
TypeError: Cannot read property 'instance' of undefined
    at SkyToastService../node_modules/@skyux/toast/modules/toast/toast.service.js.SkyToastService.closeAll (toast.service.js:67)
```

### Steps to reproduce
1. Open [StackBlitz for Toast component demo](https://developer.blackbaud.com/skyux/components/toast)
1. Click "Close all" button
1. Note console error

### Severity
Medium

### Impact
This could impact anyone using `closeAll`. I want to call `closeAll` when opening a modal that produces toasts on save so they don't stack if you're adding a bunch at one time, which is likely in my scenario.

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.0.4`
