### ISSUE TITLE
Toast on a constituent record does not automatically disappear when a user navigates to a different constituent record

### ISSUE THREAD

**Issue by Blackbaud-HeatherNoble** [blackbaud/skyux-toast#34]
### Expected behavior
When a SKYUX 3 toast is opened on a constituent record, it will be automatically dismissed when the user navigates to a different constituent record.

Note: This behavior only occurs on tiles that have been fully converted to SKYUX 3.

### Actual behavior
When a toast is opened on a constituent record, it is not automatically dismissed when the user navigates to a different constituent record. 

### Steps to reproduce

1. Navigate to a constituent record, and find the "Custom fields" tile.
2. Add, edit or delete a custom field to open the toast. 
3. On that same constituent page, find a link to a different constituent record (e.g., a fundraiser, spouse, or other relationship). 
4. The toast opened from the first record does not disappear when the new record is opened.

### Severity
Low. 

### Impact
This issue was initially reported by a customer as a bug; however, toasts can still be manually dismissed when the user navigates to a different constituent record.

**Comment by Blackbaud-BobbyEarl** [comment]
Thanks for the issue.  For accessibility, we suggest toasts do not auto close, unless there's a way to re-trigger/view the toast again.
