### ISSUE TITLE
AutoClose is not documented on Components site

### ISSUE THREAD

**Issue by Blackbaud-KrisMahon** [blackbaud/skyux-toast#53]
### Expected behavior
The Toast `autoClose` functionality should be documented on the [SKYUX Components website](https://developer.blackbaud.com/skyux/components/toast).  We've been wondering about this feature for a long time, only to discover that it has existed for almost 10 months, but it just isn't documented anywhere except in the code.

### Actual behavior
Missing documentation on Toast `autoClose`

### Severity
Low

### Impact
Low

[AB#1560205](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1560205)

**Comment by Blackbaud-ToddRoberts** [comment]
Toasts should not be auto-closed unless there is an alternative place for the user to access the message after the fact. Notification service handles this and has auto-closing toasts. Can you use notifications, or otherwise have a place for users to see auto-closed toasts?

**Comment by Blackbaud-KrisMahon** [comment]
I don't know anything about the notification service.  The Toast component's code [currently supports an `autoClose` property today](https://github.com/blackbaud/skyux-toast/blob/78f4963d4964e083b23f83d34a9960b9f1301933/src/app/public/modules/toast/toast.component.ts#L54), but it just isn't documented anywhere.  Are you saying that it actually shouldn't support this, and there is another alternative?  Either way, I really think the documentation needs to be clear about supported features and guidelines.

**Comment by Blackbaud-DeniseCisneros** [comment]
Addressed and merged in https://github.com/blackbaud/skyux2-docs/pull/1003
